title: 6ème Journée Interaction Humain Machine et Intelligence Artificielle
date : Mercredi 7 juin 2023
lieu : SCAI, Sorbonne Université, Paris
preposition: at
description: >-
  L’Association Francophone d’Interaction Homme-Machine (AFIHM) et l'Association Française pour l’Intelligence Artificielle (AFIA) organisent **le mercredi 7 juin 2023** la 6ème journée scientifique IHM et IA, au **Sorbonne Center for Artificial Intelligence (SCAI), Paris**. 
  
  Au programme, présentations, débats, posters et démos mettant en évidence les liens entre les deux disciplines. Chercheurs, praticiens, et étudiants sont invités à nous y rejoindre.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://example.com" # the base hostname & protocol for your site, e.g. https://example.com

theme: jekyll-theme-conference

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

conference:
  # Language
  lang: fr

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: Journée IHM et IA
      img: 'ihmia2023_logo_192x192.png'
      url: '/index' #landing page
    links:
      - name: Programme
        relative_url: /programme/
      - name: Présentations et débats
        relative_url: /presentations/
      - name: Demos et posters
        relative_url: /posters/
      - name: Intervenant·e·s
        relative_url: /intervenants/
      - name: Infos pratiques
        relative_url: /infos/
      - name: Éditions précédentes
        menu:
          - name: 2023 (actuel)
            disabled: true
          - name: 2021
            relative_url: https://ihmia21.afihm.org/
          - name: 2019
            relative_url: https://ihmia19.netlify.app/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: "twitter_preview.png" # inside /assets/images/
      open_graph: "facebook_preview.png" # inside /assets/images/

  # Main landing page
  main:
    logo: 'ihmia_logo_192x192.png'
    img: 'ihmia_logo_192x192.png'
    links:
      - name: Dépliant PDF
        relative_url: /assets/ihmia21.pdf
      - name: Programme
        relative_url: /programme/
      - name: Infos pratiques
        relative_url: /infos/
      - name: Inscriptions (à venir)
        disabled: true
        absolute_url: ""

  # Information boxes
  # info_bars:
  #   - title: Welcome to the Conference Theme for Jekyll!
  #     color: secondary
  #     main_only: true
  #     text: |
  #       The Theme was originally made for the [Winterkongress](https://www.digitale-gesellschaft.ch/kongress/), a yearly conference of the [Digital Society Switzerland](https://digitale-gesellschaft.ch/).

  #       ---

  #       See the [README](github.com/DigitaleGesellschaft/jekyll-theme-conference/) on the project's GitHub repository for further information on how to configure and adapt it to your needs.
  #   - text: This is just some random content for demonstration purposes.
  #     color: secondary
  #     pages_only: true

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop: 240 # in minutes
    streaming:
      enable: true
      pause: 60 # in minutes
      prepend: 5 # in minutes
      extend: 5 # in minutes
    demo:
      enable: false
      duration: 300 # in seconds
      pause: 10 # in seconds

  map:
    # Initial map center point
    home_coord: 47.37808, 8.53935
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 17

  talks:
    # Talk categories
    main_categories:
      - name: "Cat A" #"Thème 1: Concevoir des interactions avec et pour l'IA"
        color: 'theme1'
      - name:  "Cat B" # "Thème 2: Construire, évaluer et déployer des IAs dignes de confiance"
        color: 'theme2'
      # - name: "Pause"
      #   color: "Gray"
      # - name: "Posters et démos"
      #   color: "Gray". Are not categories!
    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: "/infos"
    # Main page title shown on location/room navigation bar
    navbar_title: "Infos pratiques"
    # Show map on location main page
    map: true

  program:
    # URL of program page
    url: "/programme"

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
