title: 6ème Journée Interaction Humain Machine et Intelligence Artificielle
date : Mercredi 7 juin 2023
lieu : SCAI, Sorbonne Université, Paris
preposition: at
description: >
  L’Association Francophone d’Interaction Humain-Machine (AFIHM) et l'Association Française pour l’Intelligence Artificielle (AFIA) organisent **le mercredi 7 juin 2023** la 6ème journée scientifique IHM et IA, au **Sorbonne Center for Artificial Intelligence (SCAI), Paris**. 
  
  Au programme, présentations, débats, posters et démos mettant en évidence les liens entre les deux disciplines. Chercheurs, praticiens, et étudiants sont invités à nous y rejoindre.

  <h5>Tarifs</h5>
  
  - *Gratuit* pour les adhérents de l'AFIHM ou de l'AFIA → Adhérer à l'[AFIHM](https://www.afihm.org/tarifsetmodedepaiement.shtml) ou l'[AFIA](https://afia.asso.fr/adhesion/).

  - *30€* pour les non-adhérents (à payer lors de la confirmation par mail)

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ihmia23.afihm.org/" # the base hostname & protocol for your site, e.g. https://example.com

# Google Analytics
google_analytics_id: G-X1T3NJHZ6K # Start with G-XXXXXXXXXX

theme: jekyll-theme-conference

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  posters:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: posters
    values:
      layout: poster
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

conference:
  # Language
  lang: fr

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: Journée IHM et IA
      img: 'ihmia2023_logo_192x192.png'
      url: '/index' #landing page
    links:
      - name: Accueil
        relative_url: /index
      - name: Présentations et débats
        relative_url: /presentations/
      - name: Déroulé
        relative_url: /programme/
      - name: Posters
        relative_url: /posters/
      - name: Intervenant·e·s
        relative_url: /intervenants/
      - name: Infos pratiques
        relative_url: /infos/
      - name: Éditions précédentes
        menu:
          - name: 2023
            disabled: true
          - name: 2021
            relative_url: https://ihmia21.afihm.org/
          - name: 2019
            relative_url: https://ihmia19.netlify.app/
          - name: 2017
            relative_url: https://ihmia17.netlify.app/
          - name: 2015
            relative_url: /assets/archive2015/report_ihmia_2015.pdf
          - name: 2013
            relative_url: http://interaction.lille.inria.fr/events/IHMIA13/programme/index.html

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: "twitter_preview.png" # inside /assets/images/
      open_graph: "facebook_preview.png" # inside /assets/images/

  # Main landing page
  main:
    logo: 'ihmia_logo_192x192.png'
    img: 'ihmia_logo_192x192.png'
    links:
      - name: Dépliant PDF
        relative_url: /assets/communication2023/flyer-ihmia2023-A4.pdf
        target: "_blank"
      # - name: Programme
      #   relative_url: /programme/
      - name: Infos pratiques
        relative_url: /infos/


  # Information boxes
  info_bars:
    - title: Replay vidéo de la journée 🎥
      color: secondary
      text: |

        Les présentations et débats de la journée sont maintenant disponibles en replay sur <a href="https://www.youtube.com/channel/UCFJ6Mm-eycVYK4rCVve2s2g" target="_blank">la chaîne YouTube de la journée IHM-IA</a> !

      pages_only: false

  # Live indications
  live:
    date: 03.03.2023
    timezone: GMT+1
    stop: 10 # in minutes
    streaming:
      enable: false
      pause: 0 # in minutes
      prepend: 1 # in minutes
      extend: 1 # in minutes
    demo:
      enable: false
      duration: 60 # in seconds
      pause: 0 # in seconds

  # map:
  #   # Initial map center point
  #   home_coord: 47.37808, 8.53935
  #   # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
  #   # The following do match the Bootstrap design not too badly:
  #   #   - Hydda.Full
  #   #   - Thunderforest.Neighbourhood
  #   #   - Esri.WorldTopoMap
  #   map_provider: "OpenStreetMap.Mapnik"
  #   default_zoom: 17

  talks:
    # Talk categories
    main_categories:
      - name: "Thème 1"
        fullname: "Concevoir des interactions avec et pour l'IA"
        color: 'theme1'
      - name:  "Thème 2"
        fullname: "Construire, évaluer, et déployer des IAs de confiance"
        color: 'theme2'
      - name: "Pause"
        color: "pauses"
    # Hide icons on talk overview page
    hide_icons: false

  posters:
    main_categories:
      - name: "Posters"
        color: "primary"
      # - name: "Démos"
      #   color: "secondary"

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: "/infos"
    # Main page title shown on location/room navigation bar
    navbar_title: "Infos pratiques"
    # Show map on location main page
    map: false

  program:
    # URL of program page
    url: "/programme"

    # Time steps in program table
    time_steps: 5 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true


organizers:
  - name: "Téo Sanchez"
    email: "teo.eoures@gmail.com"
    organization: "AFIHM"
  - name: "Benoît Le Blanc"
    email: "benoit.leblanc@ensc.fr"
    organization: "AFIA"
  - name: "Eya Ben Chaaben"
    email: "eya.ben-chaaben@inria.fr"
    organization: "AFIA"

partners:
  - acronym: AFIHM
    name: Association Francophone d'Interaction Humain-Machine
    url: https://www.afihm.org/
    logo: "afihm_logo.png"
  - acronym: AFIAafihm
    name: Association Française pour l'Intelligence Artificielle
    url: https://afia.asso.fr/
    logo: "afia_logo.png"
  - acronym: SCAI
    name: Sorbonne Center for Artificial Intelligence
    url: https://scai.sorbonne-universite.fr/
    logo: "scai_logo.svg"
  # - acronym: INP Bordeaux ENSC
  #   name: Institut National Polytechnique de Bordeaux
  #   url: https://ensc.bordeaux-inp.fr/fr
  #   logo: "ensc_logo_v2.png"
